[package]
name = "parser-openapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Inflector = { version = "0.11", default-features = false }
dynaql = { path = "../dynaql", features = ["tracing_worker"] }
indexmap = "1.9"
once_cell = "1.17"
openapiv3 = "1"
petgraph = "0.6"
regex = "1.7"
serde_json = "1"
serde_yaml = "0.9"
strum = { version = "0.24", features = ["derive"] }
thiserror = { workspace = true }
url = "2.3"

[dev-dependencies]
insta = "1"
rstest = "0.17"
