[package]
name = "test_dyql"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-graphql = { path = "../../../dynaql", features = ["tracing_worker"] }
aws-region-nearby = "0.1"
log = { path = "../../../log" }
dynamodb = { path = "../../../dynamodb" }
worker = "0.0.11"
serde_json = "1"
