[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
dynaql-parser = { path = "../dynaql/parser" }
dynaql-value = { path = "../dynaql/value" }
dynaql = { path = "../dynaql", features = ["tracing_worker"] }
case = "1"
if_chain = "1"
quick-error = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = { version = "2" }

[dev-dependencies]
insta = "1"
pretty_assertions = "1"
serde_json = "1"
