[package]
name = "gateway-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-region-nearby = { workspace = true }
dynaql = { path = "../dynaql" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
worker = { workspace = true }

grafbase = { path = "../grafbase", features = ["json"] }
