[package]
name = "gateway-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-region-nearby = { workspace = true }
dynaql = { path = "../dynaql" }
rusoto_core = { workspace = true }
serde = { version = "1", features = ["derive"] }
worker = { workspace = true }
ulid = { workspace = true }

grafbase = { path = "../grafbase", features = ["json"] }
