[package]
name = "gateway-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-region-nearby = { workspace = true }
dynaql = { path = "../dynaql" }
rusoto_core = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
worker = { workspace = true }
ulid = { workspace = true }

grafbase = { path = "../grafbase", features = ["json"] }

[dev-dependencies]
sha2 = { version = "0.10", default-features = false }
serde_json = { version = "1", default-features = false }
