[package]
name = "gateway-adapter"
description = "An adapter layer between the gateway and its environment"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
futures-util = { workspace = true }
rusoto_core = { workspace = true }
serde = { version = "1", features = ["derive"] }
thiserror = { workspace = true }
worker = { workspace = true }

engine = { workspace = true }
gateway-core = { workspace = true }
common-types = { workspace = true }
