[package]
name = "grafbase-types"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true, features = ["derive"] }
