[package]
name = "production-server"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
ascii = { version = "1.1.0", features = ["serde"] }
async-trait = "0.1.77"
axum = { workspace = true, features = ["macros", "ws"] }
axum-server = { version = "0.6.0", features = ["tls-rustls"] }
duration-str = "0.7.1"
engine.workspace = true
engine-config-builder.workspace = true
engine-v2.workspace = true
futures-util.workspace = true
gateway-core.workspace = true
gateway-v2 = { workspace = true, features = ["axum"] }
graphql-composition.workspace = true
http.workspace = true
parser-sdl = { version = "0.1.0", path = "../../../engine/crates/parser-sdl" }
reqwest = { workspace = true, default-features = false, features = ["rustls-tls", "gzip", "json"] }
runtime.workspace = true
runtime-local.workspace = true
runtime-noop.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "signal", "time", "net"] }
toml = "0.8.10"
tower-http = { version = "0.5.2", features = ["cors"] }
tracing.workspace = true
ulid = { workspace = true, features = ["serde"] }
url = { workspace = true, features = ["serde"] }

[dev-dependencies]
indoc = "2.0.4"
insta.workspace = true
