[package]
name = "dynaql-derive"
version = "3.0.31"
edition = "2021"
description = "Macros for dynaql"
repository = "https://github.com/grafbase/api"
license = "MPL-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
syn = { version = "2", features = [
    "full",
    "extra-traits",
    "visit-mut",
    "visit",
] }
quote = "1"
Inflector = { version = "0.11", default-features = false }
proc-macro-crate = "1"
darling = "0.20"
thiserror = { workspace = true }
