[package]
name = "grafbase-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
thiserror = { workspace = true }

grafbase = { workspace = true }
search-protocol = { path = "../search/protocol" }
