[package]
name = "runtime-ext"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
async-trait = "0.1"
thiserror = { workspace = true }
strum = { workspace = true, features = ["derive"] }
engine = { workspace = true }

[features]
test-utils = []
