[package]
name = "grafbase-local"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
grafbase-runtime = { workspace = true }
gateway-protocol = { workspace = true }
registry-provider = { workspace = true }
send_wrapper = "0.6"
serde = { workspace = true }
serde_json = { workspace = true }
log = { path = "../../log", features = ["with-worker"] }
worker = { workspace = true }
search-protocol = { path = "../../search/protocol" }
graph-entities = { path = "../../../common/graph-entities" }
worker-utils = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
reqwest = { version = "0.11", default-features = false, features = ["json"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
reqwest = { version = "0.11", default-features = false, features = [
  "json",
  "rustls-tls",
] }
