[package]
name = "grafbase-local"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
grafbase-runtime = { path = ".." }
serde = { workspace = true }
log = { path = "../../log", features = ["with-worker"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
surf = { version = "2", default-features = false, features = ["wasm-client"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
surf = { version = "2", default-features = false, features = [
  "h1-client-rustls",
] }
