[package]
name = "tracing"
authors = ["Grafbase"]
description = "Tracing capabilities for Grafbase"
version = "0.1.0"
edition = "2021"
homepage = "https://grafbase.com"
repository = "https://github.com/grafbase/grafbase"
keywords = ["tracing", "grafbase"]

[lints]
workspace = true

[dependencies]
http.workspace = true
http-body = "1.0.0"
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
# can't use .22 due to https://github.com/cloudflare/workers-rs/issues/439 ...
# tracing-otel uses js-sys ^0.3.64 but worker.wasm-bindgen =0.2.86 has a lower version
tracing-opentelemetry = "0.21.0"
# the versions below are affected by the above ...
opentelemetry = "0.20"
opentelemetry_sdk = { version = "0.20", features = ["rt-tokio"] }
opentelemetry-stdout = { version = "0.1", features = ["trace"] }
opentelemetry-otlp = { version = "0.13" , features = ["grpc-tonic"] }
tower-http = { workspace = true, optional = true }

[features]
default = []
tower = ["tower-http"]