[package]
name = "grafbase-graphql-introspection"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
indoc = "2.0.4"
reqwest = { version = "0.11.23", default-features = false, features = ["json", "rustls"] }
cynic = { version = "3.3.3", features = ["http-reqwest"] }
cynic-introspection = "3.3.3"
serde = "1.0.195"
apollo-parser = "0.7.5"
apollo-encoder = "0.8.0"

