[package]
name = "generate_registry"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = { path = "../../../dynaql", features = ["tracing_worker"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1"
