[package]
name = "grafbase-gateway"
version = "0.1.0-rc.20"
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

[features]
lambda = ["federated-server/lambda", "tracing-subscriber/json"]

[dependencies]
anyhow = { version = "1.0.81", default-features = false }
ascii = { version = "1.1.0", default-features = false }
clap = { version = "4", default-features = false, features = ["std", "cargo", "wrap_help", "derive", "env"] }
federated-server.workspace = true
grafbase-tracing = { workspace = true, features = ["otlp"] }
graph-ref.workspace = true
mimalloc = "0.1.39"
rustls = { workspace = true, features = ["ring"] }
tokio = { workspace = true, features = ["rt-multi-thread"] }
toml = "0.8.12"
tracing-subscriber.workspace = true

[lints]
workspace = true

[dev-dependencies]
duct = "0.13.7"
futures-util.workspace = true
indoc = "2.0.4"
serde_json.workspace = true
tempfile = "3.10.1"
wiremock.workspace = true
insta = { workspace = true, features = ["json", "redactions", "yaml"] }
fslock = "0.2.1"
reqwest.workspace = true
http.workspace = true
serde.workspace = true
grafbase-graphql-introspection.workspace = true
ctor.workspace = true
