[package]
name = "grafbase-sdk-integration-tests"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
console_error_panic_hook = "0.1"
serde = { workspace = true }
serde_json = { workspace = true }
serde-wasm-bindgen = { workspace = true }
worker = { workspace = true }

grafbase-sdk = { path = "../grafbase-sdk" }