[tasks.pnpm-install]
command = "pnpm"
args = ["install"]

[tasks.fmt]
dependencies = ["fmt-rust", "fmt-js"]

[tasks.build]
dependencies = ["fmt", "build-worker-rust", "build-worker-js"]

[tasks.test]
command = "npx"
args = ["vitest", "run"]
dependencies = ["pnpm-install", "build"]

### RUST
[tasks.fmt-rust]
command = "cargo"
args = ["fmt"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]

[tasks.build-worker-rust]
command = "worker-build"
args = ["--dev"]

[tasks.serve-rust]
command = "wrangler"
args = ["dev"]
dependencies = ["build-worker-rust"]

### JS
[tasks.fmt-js]
command = "npm"
args = ["run", "fmt"]

[tasks.build-worker-js]
cwd = "./js/"
command = "wrangler"
args = ["deploy", "--dry-run", "--outdir=dist"]
dependencies = ["bundle-grafbase-sdk"]

[tasks.bundle-grafbase-sdk]
cwd = "../grafbase-sdk"
command = "cargo"
args = ["make", "bundle"]

[tasks.serve-js]
cwd = "./js/"
command = "wrangler"
args = ["dev"]
dependencies = ["build-worker-js"]