name = "grafbase-sdk-rust-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2023-08-18"

kv_namespaces = [
  { binding = "TEST_NAMESPACE", id = "<ignored>", preview_id = "<ignored>" }
]

[vars]
KV_ID = "TEST_NAMESPACE"