[package]
name = "postgres-connector-types"
description = "Shared types for Postgres connector"
version = "0.1.0"
edition = "2021"
authors = ["Grafbase"]
license = "MPL-2.0"
homepage = "https://grafbase.com"
repository = "https://github.com/grafbase/grafbase"
keywords = ["graphql", "postgres", "grafbase"]

[lints]
workspace = true

[dependencies]
Inflector = "0.11.4"
async-trait = "0.1.77"
async-stream = "0.3"
async-runtime.workspace = true
flexbuffers.workspace = true
futures.workspace = true
indexmap = { workspace = true, features = ["serde"] }
itertools.workspace = true
search-protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
url.workspace = true
tracing.workspace = true

[features]
pooling = ["deadpool-postgres"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
reqwest = { version = "0.11", default-features = false, features = ["json"] }
# https://github.com/sfackler/rust-postgres/pull/1067
tokio-postgres = { git = "https://github.com/grafbase/rust-postgres/", branch = "grafbase", features = ["js"], default-features = false }
worker.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
rustls = "0.22.2"
rustls-native-certs = "0.7.0"
# https://github.com/sfackler/rust-postgres/pull/1067
tokio-postgres = { git = "https://github.com/grafbase/rust-postgres/", branch = "grafbase" }
tokio-postgres-rustls = { git = "https://github.com/grafbase/tokio-postgres-rustls", branch = "grafbase-tokio-postgres" }
deadpool-postgres = { git = "https://github.com/hfgbarrigas/deadpool/", branch = "grafbase", optional = true}
