[package]
name = "dataloader"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-trait = { version = "0.1", default-features = false }
fnv = { version = "1", default-features = false, features = ["std"] }
futures-channel = { version = "0.3", default-features = false }
futures-timer = { version = "3", default-features = false, features = ["wasm-bindgen"] }
futures-util = { workspace = true, features = ["io", "sink"] }
lru = { version = "0.11", default-features = false }
tracing = { workspace = true, optional = true }

[dev-dependencies]
tokio = { version = "1.32", features = [
  "macros",
  "rt-multi-thread",
  "sync",
  "time",
] }
async-graphql = "6"

[features]
tracing = ["dep:tracing"]