[package]
name = "gatewaylib"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1"
jwt-verifier = { workspace = true }
engine = { workspace = true }
thiserror = { workspace = true }
runtime = { workspace = true }
common-types = { workspace = true }
serde_json = { workspace = true }
futures-util = { workspace = true }
tracing = { workspace = true }
send_wrapper = { version = "0.6", features = ["futures"] }
log = { workspace = true, features = ["with-worker"] }
gateway-adapter = { workspace = true }
runtime-ext = { workspace = true }
rusoto_core = { workspace = true }
engine-value = { workspace = true }

# admin endpoint
async-graphql = { version = "6", features = ["url"] }
http = "0.2"

# FIXME: shouldn't be present...
worker = { workspace = true }

[dev-dependencies]
runtime-ext = { workspace = true, features = ["test-utils"] }
anyhow = { workspace = true }
serde = { workspace = true }
gateway-adapter-platform = { workspace = true }
tokio = { workspace = true, features = ["full"] }
