[package]
name = "async-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = { version = "0.4" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1" }
