[package]
name = "parser-postgresql"
description = "Grafbase schema introspection for PostgreSQL database"
version = "0.1.0"
edition = "2021"
authors = ["Grafbase"]
license = "MPL-2.0"
homepage = "https://grafbase.com"
repository = "https://github.com/grafbase/grafbase"
keywords = ["graphql", "parser", "postgresql", "grafbase"]

[dependencies]
parser-sdl = { path = "../parser-sdl" }
postgresql-types = { path = "../postgresql-types" }
serde_json.workspace = true
serde.workspace = true
