[package]
name = "dynaql"
version = "3.0.31"
authors = ["sunli <scott_s829@163.com>", "Koxiaet"]
edition = "2021"
description = "A GraphQL server library implemented in Rust"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/async-graphql/"
homepage = "https://github.com/async-graphql/async-graphql"
repository = "https://github.com/async-graphql/async-graphql"
keywords = ["futures", "async", "graphql"]
categories = ["network-programming", "asynchronous"]
readme = "README.md"

[features]
default = []
apollo_tracing = []
apollo_persisted_queries = ["lru", "sha2"]
unblock = ["blocking"]
string_number = []
dataloader = ["futures-timer", "futures-channel", "lru"]
tracing = ["tracinglib", "tracing-futures"]
decimal = ["rust_decimal"]
cbor = ["serde_cbor"]
chrono-duration = ["iso8601-duration"]
password-strength-validator = ["zxcvbn"]
unstable_oneof = ["dynaql-derive/unstable_oneof"]
tracing_worker = ["logworker"]

[dependencies]
dynaql-derive = { path = "derive", version = "3" }
dynaql-value = { path = "value", version = "3" }
dynaql-parser = { path = "parser", version = "3" }

async-stream = "0.3"
async-trait = "0.1"
derivative = "2"
dynomite = "0.10"
fnv = "1"
futures-util = { version = "0.3", default-features = false, features = ["io", "sink"] }
indexmap = "~1.6"
itertools = "0.10.3"
pin-project-lite = "0.2"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
static_assertions = "1"
http = "0.2"
multer = "2"
tempfile = "3"
bytes = { version = "1", features = ["serde"] }
mime = "0.3"
num-traits = "0.2"
fast_chemail = "0.9"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }

# API dependencies
dynamodb = { path = "../dynamodb" }
logworker = { path = "../log", package = "log", optional = true, features = ["with-worker"] }
ulid-rs = { path = "../ulid-rs" }

# Feature optional dependencies
bson = { version = "2", optional = true, features = ["chrono-0_4"] }
chrono-tz = { version = "0.6", optional = true }
hashbrown = { version = "0.12", optional = true }
iso8601-duration = { version = "0.1", optional = true }
log = { version = "0.4", optional = true }
secrecy = { version = "0.8", optional = true }
tracinglib = { version = "0.1", optional = true, package = "tracing" }
tracing-futures = { version = "0.2", optional = true, features = ["std-future", "futures-03"] }
opentelemetry = { version = "0.17", optional = true, default-features = false, features = ["trace"] }
uuid = { version = "0.8", optional = true, features = ["v4", "serde"] }
rust_decimal = { version = "1", optional = true }
url = { version = "2", optional = true }
smol_str = { version = "0.1", optional = true }
time = { version = "0.3", optional = true, features = ["parsing", "formatting", "macros"] }
futures-timer = { version = "3", optional = true }

# Non-feature optional dependencies
blocking = { version = "1", optional = true }
lru = { version = "0.7", optional = true }
sha2 = { version = "0.10", optional = true }
futures-channel = { version = "0.3", optional = true }
serde_cbor = { version = "0.11", optional = true }
zxcvbn = { version = "2", optional = true }

[dev-dependencies]
# tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time"] }
# futures-channel = "0.3"
once_cell = "1"
