[package]
name = "async-graphql"
version = "3.0.31"
authors = ["sunli <scott_s829@163.com>", "Koxiaet"]
edition = "2021"
description = "A GraphQL server library implemented in Rust"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/async-graphql/"
homepage = "https://github.com/async-graphql/async-graphql"
repository = "https://github.com/async-graphql/async-graphql"
keywords = ["futures", "async", "graphql"]
categories = ["network-programming", "asynchronous"]
readme = "README.md"

[features]
default = []
apollo_tracing = []
apollo_persisted_queries = ["lru", "sha2"]
unblock = ["blocking"]
string_number = []
dataloader = ["futures-timer", "futures-channel", "lru"]
tracing = ["tracinglib", "tracing-futures"]
decimal = ["rust_decimal"]
cbor = ["serde_cbor"]
chrono-duration = ["iso8601-duration"]
password-strength-validator = ["zxcvbn"]
unstable_oneof = ["async-graphql-derive/unstable_oneof"]
tracing_worker = ["logworker"]

[dependencies]
async-graphql-derive = { path = "derive", version = "3.0.31" }
async-graphql-value = { path = "value", version = "3.0.31" }
async-graphql-parser = { path = "parser", version = "3.0.31" }

async-stream = "0.3.0"
async-trait = "0.1.48"
derivative = "2.2"
dynamodb = { path = "../api/common/dynamodb" }
# dynamodb = { git = "ssh://git@github.com/grafbase/api", rev = "20ab6484c6578f4106c2313fe2c34a5dba706833" }
dynomite = { git = "https://github.com/softprops/dynomite.git" }
fnv = "1.0.7"
futures-util = { version = "0.3.0", default-features = false, features = ["io", "sink"] }
indexmap = "~1.6.2"
pin-project-lite = "0.2.6"
regex = "1.4.5"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
thiserror = "1.0.24"
static_assertions = "1.1.0"
http = "0.2.3"
multer = "2.0.0"
tempfile = "3.2.0"
bytes = { version = "1.0.1", features = ["serde"] }
mime = "0.3.15"
num-traits = "0.2.14"
fast_chemail = "0.9.6"
ulid = "0.5.0"
chrono = { version = "0.4.19", default-features = false, features = ["clock", "std"] }


# Feature optional dependencies
bson = { version = "2.0.0", optional = true, features = ["chrono-0_4"] }
chrono-tz = { version = "0.5.3", optional = true }
hashbrown = { version = "0.12.0", optional = true }
iso8601-duration = { version = "0.1.0", optional = true }
log = { version = "0.4.14", optional = true }
secrecy = { version = "0.8.0", optional = true }
tracinglib = { version = "0.1.25", optional = true, package = "tracing" }
logworker = { git = "ssh://git@github.com/grafbase/api", branch = "main", package = "log", optional = true, features = ["with-worker"] }
tracing-futures = { version = "0.2.5", optional = true, features = ["std-future", "futures-03"] }
opentelemetry = { version = "0.17.0", optional = true, default-features = false, features = ["trace"] }
uuid = { version = "0.8.2", optional = true, features = ["v4", "serde"] }
rust_decimal = { version = "1.14.3", optional = true }
url = { version = "2.2.1", optional = true }
smol_str = { version = "0.1.21", optional = true }
time = { version = "0.3.5", optional = true, features = ["parsing", "formatting", "macros"] }
futures-timer = { version = "3.0.2", optional = true }

# Non-feature optional dependencies
blocking = { version = "1.0.2", optional = true }
lru = { version = "0.7.1", optional = true }
sha2 = { version = "0.10.2", optional = true }
futures-channel = { version = "0.3.13", optional = true }
serde_cbor = { version = "0.11.1", optional = true }
zxcvbn = { version = "2.1.2", optional = true }

[dev-dependencies]
# tokio = { version = "1.4.0", features = ["macros", "rt-multi-thread", "sync", "time"] }
# futures-channel = "0.3.13"
once_cell = "1.10.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[patch."ssh://git@github.com/grafbase/dynaql"]
async-graphql = { path = "." }

[workspace]
members = [
    "value",
    "parser",
    "derive",
#   "integrations/poem",
#   "integrations/actix-web",
#   "integrations/rocket",
#   "integrations/warp",
#   "integrations/axum",
#   "integrations/tide",
]
