[package]
name = "dynaql-derive"
version = "3.0.31"
authors = ["sunli <scott_s829@163.com>", "Koxiaet"]
edition = "2021"
description = "Macros for async-graphql"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/async-graphql/"
homepage = "https://github.com/async-graphql/async-graphql"
repository = "https://github.com/async-graphql/async-graphql"
keywords = ["futures", "async", "graphql"]
categories = ["network-programming", "asynchronous"]

[lib]
proc-macro = true

[features]
unstable_oneof = []

[dependencies]
proc-macro2 = "1"
syn = { version = "1", features = ["full", "extra-traits", "visit-mut", "visit"] }
quote = "1"
Inflector = { version = "0.11", default-features = false }
proc-macro-crate = "1"
darling = "0.20"
thiserror = { workspace = true }
