[package]
name = "dynamodb"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = "0.3"
aws-region-nearby = "0.1"
composite-id = { path = "../composite-id", features = ["with-dynomite", "with-named-type"] }
dynomite = { git = "https://github.com/softprops/dynomite.git" }
futures-util = { version = "0.3", default-features = false, features = ["std", "async-await"] }
log = { path = "../log" }
quick-error = "2"
rusoto_core = "0.47"
rusoto_dynamodb = "0.47"
serde = { version = "1", features = ["derive"] }
strum = { version = "0.24", features = ["derive"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
surf = { version = "2", default-features = false, features = ["wasm-client"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
surf = { version = "2", default-features = false, features = ["h1-client-rustls"] }
