[package]
name = "dynamodb"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = "0.3"
async-trait = "0.1"
aws-region-nearby = "0.1"
composite-id = { path = "../composite-id", features = ["with-dynomite", "with-named-type"] }
dynomite = { git = "https://github.com/softprops/dynomite.git" }
fnv = "1"
futures = "0.3"
futures-channel = { version = "0.3" }
futures-timer = { version = "3", features = ["wasm-bindgen"] }
futures-util = { version = "0.3", default-features = false, features = ["std", "async-await"] }
indexmap = "~1.6.2"
log = { path = "../log", features = ["with-worker"] }
lru = { version = "0.7" }
quick-error = "2"
rusoto_core = "0.48"
rusoto_dynamodb = "0.48"
serde = { version = "1", features = ["derive"] }
strum = { version = "0.24", features = ["derive"] }
wasm-bindgen-futures = "0.4"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
surf = { version = "2", default-features = false, features = ["wasm-client"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
surf = { version = "2", default-features = false, features = ["h1-client-rustls"] }
