[package]
name = "dynamodb"
version = "0.1.0"
edition = "2021"

[dependencies]
again = { git = "https://github.com/Miaxos/again", default-features = false, features = [
    "wasm-bindgen",
    "log",
] }
async-trait = "0.1"
aws-region-nearby = "0.1"
chrono = { version = "0.4", default-features = false, features = [
    "clock",
    "std",
] }
derivative = "2.2"
dynomite = "0.10"
fnv = "1"
futures = "0.3"
futures-channel = { version = "0.3" }
futures-timer = { version = "3", features = ["wasm-bindgen"] }
futures-util = { version = "0.3", default-features = false, features = [
    "std",
    "async-await",
] }
indexmap = "~1.9"
itertools = "0.10"
log = { path = "../log", features = ["with-worker"] }
lru = { version = "0.7" }
quick-error = "2"
rusoto_core = "0.48"
rusoto_dynamodb = "0.48"
serde_json = "1"
thiserror = "1"
tracing = "0.1"
wasm-bindgen-futures = "0.4"

# feature="local"
cfg-if = "1"
indoc = { version = "1", optional = true }
once_cell = { version = "1", optional = true }
regex = { version = "1", optional = true }
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "time",
] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
surf = { version = "2", default-features = false, optional = true, features = [
    "wasm-client",
] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
surf = { version = "2", default-features = false, optional = true, features = [
    "h1-client-rustls",
] }

[features]
default = []
local = ["indoc", "once_cell", "regex", "serde", "surf"]
