[package]
name = "dynaql-parser"
version = "3.0.31"
edition = "2021"
description = "GraphQL query parser for dynaql"
repository = "https://github.com/grafbase/api"
license = "MPL-2.0"

[dependencies]
dynaql-value = { path = "../value", version = "3" }
pest = "2"
pest_derive = "2"
serde = { workspace = true }
