name: Sanitize and test
description: Run cargo fmt, clippy, test

inputs:
  lint:
    required: false
    default: 'true'
    description: To run fmt/clippy or not to run
  test-engine:
    required: false
    default: 'false'
    description: To run test or not to run
  test-grafbase:
    required: false
    default: 'false'
    description: To run test or not to run
  test-grafbase-gateway:
    required: false
    default: 'false'
    description: To run test or not to run
  dockerhub-username:
    required: true
    description: Username to log into docker hub
  dockerhub-token:
    required: true
    description: Token to log into docker hub

runs:
  using: 'composite'
  steps:
    - name: Build udf-wrapper
      shell: bash
      working-directory: './cli/udf-wrapper'
      run: |
        npm i
        npm run build

    - if: ${{ inputs.lint == 'true' }}
      name: cargo fmt
      shell: bash
      run: |
        cargo fmt --check

    - if: ${{ inputs.lint == 'true' }}
      name: cargo clippy
      shell: bash
      run: |
        cargo clippy \
          --workspace \
          --exclude integration-tests \
          --locked \
          --all-targets \
          --tests -- -D warnings

    # https://github.com/actions/setup-node/issues/899
    - name: Enable Corepack before setting up Node
      if: ${{ inputs.test-grafbase-gateway == 'false' }}
      shell: bash
      run: corepack enable

    - name: Setup Node.js
      if: ${{ inputs.test-grafbase-gateway == 'false' }}
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install pnpm
      if: ${{ inputs.test-grafbase-gateway == 'false' }}
      uses: pnpm/action-setup@v2
      id: pnpm-install
      with:
        version: 8
        run_install: false

    - name: Login to Docker Hub
      if: ${{ inputs.test-engine == 'true' }}
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}

    - name: Start local databases
      shell: bash
      if: ${{ inputs.test-engine == 'true' }}
      run: |
        docker-compose -f engine/crates/integration-tests/docker-compose.yml up -d

    - if: ${{ inputs.test-engine == 'true' }}
      name: test engine
      shell: bash
      run: |
        RUST_BACKTRACE=1 cargo nextest run --workspace \
          --exclude federated-server \
          --exclude grafbase-gateway \
          --exclude grafbase-local-backend \
          --exclude grafbase \
          --exclude grafbase-local-common \
          --exclude federated-dev \
          --exclude gateway \
          --exclude grafbase-graphql-introspection \
          --exclude grafbase-local-server \
          --exclude typed-resolvers \
          --profile ci

    - if: ${{ inputs.test-grafbase == 'true' }}
      name: test grafbase
      shell: bash
      run: |
        RUST_BACKTRACE=1 cargo nextest run --workspace \
          --exclude integration-tests \
          --exclude graph-ref \
          --exclude graphql-introspection \
          --exclude federated-server \
          --exclude grafbase-gateway \
          --exclude async-runtime \
          --exclude common-types \
          --exclude graphql-composition \
          --exclude dataloader \
          --exclude engine-config-builder \
          --exclude engine-v2 \
          --exclude engine-v2-config \
          --exclude engine-v2-schema \
          --exclude engine \
          --exclude engine-derive \
          --exclude engine-parser \
          --exclude engine-value \
          --exclude graphql-federated-graph \
          --exclude gateway-core \
          --exclude gateway-v2-auth-config \
          --exclude gateway-v2-auth \
          --exclude gateway-v2 \
          --exclude graph-entities \
          --exclude graphql-extensions \
          --exclude graphql-mocks \
          --exclude graphql-schema-diff \
          --exclude jwt-verifier \
          --exclude log \
          --exclude operation-checks \
          --exclude operation-normalizer \
          --exclude parser-graphql \
          --exclude parser-openapi \
          --exclude parser-postgres \
          --exclude parser-sdl \
          --exclude postgres-connector-types \
          --exclude runtime-local \
          --exclude runtime-noop \
          --exclude runtime \
          --exclude runtime \
          --exclude grafbase-tracing \
          --exclude graphql-schema-validation \
          --profile ci

    - if: ${{ inputs.test-grafbase-gateway == 'true' }}
      name: test grafbase-gateway
      shell: bash
      run: |
        RUST_BACKTRACE=1 cargo nextest run --workspace \
          --exclude integration-tests \
          --exclude graph-ref \
          --exclude graphql-introspection \
          --exclude grafbase-local-backend \
          --exclude grafbase \
          --exclude grafbase-local-common \
          --exclude federated-dev \
          --exclude gateway \
          --exclude grafbase-graphql-introspection \
          --exclude grafbase-local-server \
          --exclude typed-resolvers \
          --exclude async-runtime \
          --exclude common-types \
          --exclude graphql-composition \
          --exclude dataloader \
          --exclude engine-config-builder \
          --exclude engine-v2 \
          --exclude engine-v2-config \
          --exclude engine-v2-schema \
          --exclude engine \
          --exclude engine-derive \
          --exclude engine-parser \
          --exclude engine-value \
          --exclude graphql-federated-graph \
          --exclude gateway-core \
          --exclude gateway-v2-auth-config \
          --exclude gateway-v2-auth \
          --exclude gateway-v2 \
          --exclude graph-entities \
          --exclude graphql-extensions \
          --exclude graphql-mocks \
          --exclude graphql-schema-diff \
          --exclude jwt-verifier \
          --exclude log \
          --exclude operation-checks \
          --exclude operation-normalizer \
          --exclude parser-graphql \
          --exclude parser-openapi \
          --exclude parser-postgres \
          --exclude parser-sdl \
          --exclude postgres-connector-types \
          --exclude runtime-local \
          --exclude runtime-noop \
          --exclude runtime \
          --exclude runtime \
          --exclude grafbase-tracing \
          --exclude graphql-schema-validation \
          --profile ci
