[package]
name = "grafbase-local"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
async-trait = "0.1"

send_wrapper = "0.6"
serde = { workspace = true }
serde_json = { workspace = true }
worker = { workspace = true }

grafbase-runtime = { workspace = true }
graph-entities = { path = "../../../oss/graph-entities" }
gateway-protocol = { workspace = true }
log = { path = "../../log", features = ["with-worker"] }
registry-provider = { workspace = true }
search-protocol = { path = "../../search-protocol" }
worker-utils = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
reqwest = { version = "0.11", default-features = false, features = ["json"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
reqwest = { version = "0.11", default-features = false, features = [
  "json",
  "rustls-tls",
] }
