[package]
name = "graphql-extensions"
description = "Has extensions to be used on dynaql"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
lazy_static = "1"
wasm-timer = "0.2"

dynaql = { path = "../../oss/dynaql", default-features = false }
dynaql-value = { workspace = true }
log = { path = "../../oss/log", features = ["with-worker"] }
grafbase = { path = "../../oss/grafbase", features = ["json"] }
grafbase-runtime = { workspace = true }

[features]
local = []
