[package]
name = "graphql-extensions"
description = "Has extensions to be used on grafbase-engine"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
async-trait = "0.1"
lazy_static = "1"
web-time = { workspace = true }

grafbase-engine = { path = "../../oss/grafbase-engine", default-features = false }
grafbase-engine-value = { workspace = true }
log = { path = "../../oss/log", features = ["with-worker"] }
grafbase = { path = "../../oss/grafbase", features = ["json"] }
grafbase-runtime = { workspace = true }

[features]
local = []
