[package]
name = "gateway-v2"
authors = ["Grafbase"]
description = "Gateway v2"
edition = "2021"
license = "MPL-2.0"
homepage = "https://grafbase.com"
repository = "https://github.com/grafbase/grafbase"
keywords = ["graphql", "engine", "grafbase"]

[lints]
workspace = true

[dependencies]
engine = { path = "../engine" }
engine-v2 = { path = "../engine-v2" }
auth = { path = "./auth", package = "gateway-v2-auth" }
futures-util.workspace = true
runtime.workspace = true

