[package]
name = "grafbase-sdk"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
derive_builder = "0.12"
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = "0.4"
worker = { workspace = true }
thiserror = { workspace = true }
