[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["fmt", "clippy"]

[tasks.fmt]
command = "cargo"
args = ["fmt"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]

[tasks.build-wasm]
command = "wasm-pack"
args = ["build", "--target", "web", "--release", "--out-name", "index"]

[tasks.bundle]
command = "esbuild"
args = [
  "--external:./pkg/index_bg.wasm",
  "--format=esm",
  "--bundle",
  "./js/shim.js",
  "--outfile=dist/shim.mjs"
]
dependencies = ["build-wasm"]

[tasks.release]
dependencies = ["bundle"]

