[workspace]
members = [
    "dynamic_schema",
    "static_schema",
    "generate_registry"
]
resolver = "2"

[patch.crates-io]
coarsetime = { git = "https://github.com/grafbase/rust-coarsetime", branch = "integer-overflow" }
rusoto_core = { git = "https://github.com/grafbase/rusoto", branch = "wasm-rustls" }
rusoto_dynamodb = { git = "https://github.com/grafbase/rusoto", branch = "wasm-rustls" }
rusoto_events = { git = "https://github.com/grafbase/rusoto", branch = "wasm-rustls" }
