compatibility_date = "2022-06-22"
name = "graphql"
type = "javascript"
workers_dev = true

[build]
command = "worker-build --release"
[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"
[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
